language: node_js
sudo: required
dist: trusty
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - npm install -g polymer-cli
  - polymer install
  - polymer lint --rules polymer-1
script:
  - xvfb-run polymer test --skip-plugin sauce
